name: Scala CI

on:
  push:
    branches: [ 'master', 'github-actions' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate build number
        uses: einaregilsson/build-number@v2
        id: buildnumber
        with:
          token: ${{secrets.github_token}}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run Tests
        run: ./gradlew scalatest

      - name: Package Plugin
        run: ./gradlew assemble

      - uses: actions/upload-artifact@v2
        with:
          name: "Git Config Commit Template IJ Plugin Bundle (build ${{ steps.buildnumber.outputs.build_number }})"
          path: build/distributions/Git_Config_Commit_Template-*.zip

      - uses: actions/upload-artifact@v2
        with:
          name: "Git Config Commit Template IJ Plugin Bundle (build ${{ steps.buildnumber.outputs.build_number }})"
          path: README.md
